#!/bin/bash

set -ex

GRADLE_PROPERTIES=$HOME"/.gradle/gradle.properties"
export GRADLE_PROPERTIES

echo "Gradle Properties should exist at $GRADLE_PROPERTIES"

if [ ! -f "$GRADLE_PROPERTIES" ]; then
    echo "Gradle Properties does not exist"

    echo "Creating Gradle Properties file..."
    touch $GRADLE_PROPERTIES

    echo "Writing TEST_API_KEY to gradle.properties..."
    echo "mavenUser=$mavenUser" >> $GRADLE_PROPERTIES
    echo "mavenPassword=$mavenPassword" >> $GRADLE_PROPERTIES
fi